coverage:
  status:
    project:
      default:
        target: 85%
    patch:
      default:
        target: 90%
        threshold: 1%

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
        threshold: 1%

  individual_components:
    - component_id: domain
      name: Domain Layer
      paths: 
        - "src/main/java/com/example/demo/domain/**"
      statuses:
        - type: project
          target: 95%
          threshold: 1%

    - component_id: application
      name: Application Layer
      paths: 
        - "src/main/java/com/example/demo/application/**"
      statuses:
        - type: project
          target: 90%
          threshold: 1%

    - component_id: infrastructure
      name: Infrastructure Layer
      paths: 
        - "src/main/java/com/example/demo/infrastructure/**"
      statuses:
        - type: project
          target: 80%
          threshold: 1%

    - component_id: presentation
      name: Presentation Layer
      paths: 
        - "src/main/java/com/example/demo/presentation/**"
      statuses:
        - type: project
          target: 85%
          threshold: 1%

# カバレッジレポートから除外するファイル
ignore:
  - "**/config/**"
  - "**/exception/**"
  - "**/*Configuration.java"
  - "**/*Properties.java"

# Pull Requestのコメント設定
comment:
  layout: "reach, diff, flags, files, footer, components"
  behavior: "default"
  require_changes: false
  require_base: true
  require_head: true
  show_carryforward_flags: true