coverage:
  status:
    project:
      default:
        target: 85%

component_management:
  default_rules:
    statuses:
      - type: project
        target: 85%
        threshold: 2%

  individual_components:
    - component_id: "domain"
      paths:
        - "demo/src/main/java/com/example/demo/domain/**"

    - component_id: "application"
      paths:
        - "demo/src/main/java/com/example/demo/application/**"

    - component_id: "infrastructure"
      paths:
        - "demo/src/main/java/com/example/demo/infrastructure/**"

    - component_id: "presentation"
      paths:
        - "demo/src/main/java/com/example/demo/presentation/**"

  # パッチカバレッジの設定
  patch:
    default:
      target: 90%
      threshold: 1%

  # カバレッジレポートから除外するファイル
  ignore:
    - "**/config/**"
    - "**/exception/**"
    - "**/*Configuration.java"
    - "**/*Properties.java"

# Pull Requestのコメント設定
comment:
  layout: "header, diff, flags, components"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  show_carryforward_flags: true 