coverage:
  status:
    project:
      default:
        target: 85%

component_management:
  default_rules:
    statuses:
      - type: project
        target: 85%

  individual_components:
    - component_id: domain
      paths: ["src/main/java/com/example/demo/domain/**"]
      statuses:
        - type: project
          target: 95%

    - component_id: application
      paths: ["src/main/java/com/example/demo/application/**"]
      statuses:
        - type: project
          target: 90%

    - component_id: infrastructure
      paths: ["src/main/java/com/example/demo/infrastructure/**"]
      statuses:
        - type: project
          target: 80%

    - component_id: presentation
      paths: ["src/main/java/com/example/demo/presentation/**"]
      statuses:
        - type: project
          target: 85%

# パッチカバレッジの設定
patch:
  default:
    target: 90%
    threshold: 1%

# カバレッジレポートから除外するファイル
ignore:
  - "**/config/**"
  - "**/exception/**"
  - "**/*Configuration.java"
  - "**/*Properties.java"

# Pull Requestのコメント設定
comment:
  layout: "reach, diff, flags, files, components, footer"
  behavior: "new"
  require_changes: true
  require_base: false
  require_head: true
  show_carryforward_flags: true
  hide_project_coverage: false 