coverage:
  status:
    project:
      default:
        target: 85%
    
    # レイヤーごとのコンポーネント設定
    component:
      default:
        target: auto
      
    individual_components:
      domain:
        paths: 
          - "src/main/java/com/example/demo/domain/**"
        target: 95%
        threshold: 1%
        if_not_found: success
        only_pulls: true
      
      application:
        paths:
          - "src/main/java/com/example/demo/application/**"
        target: 90%
        threshold: 1%
        if_not_found: success
        only_pulls: true
      
      infrastructure:
        paths:
          - "src/main/java/com/example/demo/infrastructure/**"
        target: 80%
        threshold: 2%
        if_not_found: success
        only_pulls: true
      
      presentation:
        paths:
          - "src/main/java/com/example/demo/presentation/**"
        target: 85%
        threshold: 2%
        if_not_found: success
        only_pulls: true

  # パッチカバレッジの設定
  patch:
    default:
      target: 90%
      threshold: 1%

  # カバレッジレポートから除外するファイル
  ignore:
    - "**/config/**"
    - "**/exception/**"
    - "**/*Configuration.java"
    - "**/*Properties.java"

# Pull Requestのコメント設定
comment:
  layout: "reach, diff, flags, files, components, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  show_carryforward_flags: true 