coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 60%
        threshold: 1%

component_management:
  default_rules:
    statuses:
      - type: patch
        target: auto
        threshold: 1%

  individual_components:
    - component_id: backend-domain
      name: Backend - Domain Layer
      paths: 
        - "src/main/java/com/example/demo/domain/**"
      statuses:
        - type: patch
          target: 80%
          threshold: 1%

    - component_id: backend-application
      name: Backend - Application Layer
      paths: 
        - "src/main/java/com/example/demo/application/**"
      statuses:
        - type: patch
          target: 70%
          threshold: 1%

    - component_id: backend-infrastructure
      name: Backend - Infrastructure Layer
      paths: 
        - "src/main/java/com/example/demo/infrastructure/**"
      statuses:
        - type: patch
          target: 70%
          threshold: 1%

    - component_id: backend-presentation
      name: Backend - Presentation Layer
      paths: 
        - "src/main/java/com/example/demo/presentation/**"
      statuses:
        - type: patch
          target: 70%
          threshold: 1%

    - component_id: frontend-pages
      name: Frontend - Pages
      paths:
        - "src/app/**"
      statuses:
        - type: patch
          target: 70%
          threshold: 1%

    - component_id: frontend-components
      name: Frontend - Components
      paths:
        - "src/components/**"
      statuses:
        - type: patch
          target: 70%
          threshold: 1%

    - component_id: frontend-hooks
      name: Frontend - Hooks
      paths:
        - "src/hooks/**"
      statuses:
        - type: patch
          target: 70%
          threshold: 1%

# カバレッジレポートから除外するファイル
ignore:
  - "**/config/**"
  - "**/exception/**"
  - "**/*Configuration.java"
  - "**/*Properties.java"

# Pull Requestのコメント設定
comment:
  layout: "reach, diff, flags, files, footer, components"
  behavior: "default"
  require_changes: false
  require_base: true
  require_head: true
  show_carryforward_flags: true