name: Run tests and upload coverage

on: 
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  run:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2
        continue-on-error: true
        id: validate

      - name: Retry Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v2
        if: steps.validate.outcome == 'failure'

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./nextjs-frontend

      - name: Run tests
        run: npx vitest run --coverage
        working-directory: ./nextjs-frontend

      - name: Build frontend
        run: npm run build
        working-directory: ./nextjs-frontend
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ./demo

      - name: Build with Gradle
        run: ./gradlew build
        working-directory: ./demo

      - name: Run tests with Gradle
        run: ./gradlew test jacocoTestReport
        working-directory: ./demo

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: build/reports/jacoco/test/jacocoTestReport.xml
          flags: backend
          name: codecov-umbrella
          fail_ci_if_error: false
          verbose: true
          override_commit: ${{ github.sha }}
          working-directory: ./demo

      - name: Upload frontend coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: coverage/clover.xml
          flags: frontend
          name: codecov-umbrella
          fail_ci_if_error: false
          verbose: true
          override_commit: ${{ github.sha }}
          working-directory: ./nextjs-frontend