name: Run tests and upload coverage

on: 
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  run:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2
        continue-on-error: true
        id: validate

      - name: Retry Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v2
        if: steps.validate.outcome == 'failure'

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './nextjs-frontend/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: ./nextjs-frontend

      - name: Run frontend tests with coverage
        run: npx vitest run --coverage
        working-directory: ./nextjs-frontend

      - name: Check coverage files
        run: |
          echo "Frontend coverage files:"
          ls -la coverage/
        working-directory: ./nextjs-frontend

      - name: Upload frontend coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./nextjs-frontend/coverage/clover.xml
          flags: frontend
          name: frontend-coverage
          fail_ci_if_error: true
          verbose: true

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ./demo

      - name: Build and test backend with coverage
        run: ./gradlew test jacocoTestReport
        working-directory: ./demo

      - name: Check backend coverage files
        run: |
          echo "Backend coverage files:"
          ls -la build/reports/jacoco/test/
        working-directory: ./demo

      - name: Upload backend coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./demo/build/reports/jacoco/test/jacocoTestReport.xml
          flags: backend
          name: backend-coverage
          fail_ci_if_error: true
          verbose: true